### ISSUE TITLE
CustomEmoji in MessageEntityType doesn't exist

### ISSUE THREAD

**Issue by marshlak** [Eptagone/Telegram.BotAPI#21]
Hello. When message contains custom emoji and i try to get it message type, i got an exception. 
```
System.ArgumentException: Requested value 'customemoji' was not found.
at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
at Telegram.BotAPI.AvailableTypes.MessageEntity.GetEntityType()
```
Please add CustomEmoji to enum

**Comment by Eptagone** [comment]
Oh.  You're right.  The CustomEmoji value is missing. I will add it with the next release.  Thanks for reporting it.

You can use the Type property for now.

**Comment by marshlak** [comment]
please update in nuget, issue will be fixed, but not for me xd

**Comment by Eptagone** [comment]
Hi, I am updating the package to support the new version of the bot API.  Both changes will be included in the next release.
Please be patient. :3
