### ISSUE TITLE
Error while sending a file bigger than 40 MB

### ISSUE THREAD

**Issue by mnakka9** [Eptagone/Telegram.BotAPI#3]
Hey, getting an error while sending a video bigger than 40 MB.

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..

`at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<<WriteSingleChunk>g__CompleteWriteAsync|177_1>d`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Net.Security.SslStream.<WriteAsyncChunked>d__176`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Security.SslStream.<WriteAsyncInternal>d__184`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpConnection.<WriteAsync>d__71.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<<CopyToAsync>g__WaitAsync|56_0>d.MoveNext()`

Is there a limitaion, or should I need to send in chunks? Using InputFile

**Comment by Eptagone** [comment]
Hi, what file type are you trying to send? How long is the file size exactly?
According to the official Telegram bot api, you can only upload files up to 50MB depending on the file type. You can see the limits in this link.
For your bot to send large files you have two options:
- Use file ids, for files that are already on Telegram's servers.
- Use the local server of the Bot API. This allows you to upload files up to 2000 Mb.

**Comment by mnakka9** [comment]
Yes,, Thank you
